extends Node

class_name Instruments

# Source from https://www.ccarh.org/courses/253/handout/gminstruments/
enum INSTRUMENT_TYPE {
	PIANO,
	CHROMATIC_PERCUSSION,
	ORGAN,
	GUITAR,
	BASS,
	STRINGS,
	ENSEMBLE,
	BRASS,
	REED,
	PIPE,
	SYNTH_LEAD,
	SYNTH_PAD,
	SYNTH_EFFECTS,
	ETHNIC,
	SOUND_EFFECTS,
	DRUMS,
}

const instruments: Dictionary[int, Dictionary] = {
	0: { name = 'Acoustic Grand', type = INSTRUMENT_TYPE.PIANO},
	1: { name = 'Bright Acoustic', type = INSTRUMENT_TYPE.PIANO},
	2: { name = 'Electric Grand', type = INSTRUMENT_TYPE.PIANO},
	3: { name = 'Honky-Tonk', type = INSTRUMENT_TYPE.PIANO},
	4: { name = 'Electric Piano 0', type = INSTRUMENT_TYPE.PIANO},
	5: { name = 'Electric Piano 1', type = INSTRUMENT_TYPE.PIANO},
	6: { name = 'Harpsichord', type = INSTRUMENT_TYPE.PIANO},
	7: { name = 'Clavinet', type = INSTRUMENT_TYPE.PIANO},
	8: { name = 'Celesta', type = INSTRUMENT_TYPE.CHROMATIC_PERCUSSION},
	9: { name = 'Glockenspiel', type = INSTRUMENT_TYPE.CHROMATIC_PERCUSSION},
	10: { name = 'Music Box', type = INSTRUMENT_TYPE.CHROMATIC_PERCUSSION},
	11: { name = 'Vibraphone', type = INSTRUMENT_TYPE.CHROMATIC_PERCUSSION},
	12: { name = 'Marimba', type = INSTRUMENT_TYPE.CHROMATIC_PERCUSSION},
	13: { name = 'Xylophone', type = INSTRUMENT_TYPE.CHROMATIC_PERCUSSION},
	14: { name = 'Tubular Bells', type = INSTRUMENT_TYPE.CHROMATIC_PERCUSSION},
	15: { name = 'Dulcimer', type = INSTRUMENT_TYPE.CHROMATIC_PERCUSSION},
	16: { name = 'Drawbar Organ', type = INSTRUMENT_TYPE.ORGAN},
	17: { name = 'Percussive Organ', type = INSTRUMENT_TYPE.ORGAN},
	18: { name = 'Rock Organ', type = INSTRUMENT_TYPE.ORGAN},
	19: { name = 'Church Organ', type = INSTRUMENT_TYPE.ORGAN},
	20: { name = 'Reed Organ', type = INSTRUMENT_TYPE.ORGAN},
	21: { name = 'Accoridan', type = INSTRUMENT_TYPE.ORGAN},
	22: { name = 'Harmonica', type = INSTRUMENT_TYPE.ORGAN},
	23: { name = 'Tango Accordian', type = INSTRUMENT_TYPE.ORGAN},
	24: { name = 'Nylon String Guitar', type = INSTRUMENT_TYPE.GUITAR},
	25: { name = 'Steel String Guitar', type = INSTRUMENT_TYPE.GUITAR},
	26: { name = 'Electric Jazz Guitar', type = INSTRUMENT_TYPE.GUITAR},
	27: { name = 'Electric Clean Guitar', type = INSTRUMENT_TYPE.GUITAR},
	28: { name = 'Electric Muted Guitar', type = INSTRUMENT_TYPE.GUITAR},
	29: { name = 'Overdriven Guitar', type = INSTRUMENT_TYPE.GUITAR},
	30: { name = 'Distortion Guitar', type = INSTRUMENT_TYPE.GUITAR},
	31: { name = 'Guitar Harmonics', type = INSTRUMENT_TYPE.GUITAR},
	32: { name = 'Acoustic Bass', type = INSTRUMENT_TYPE.BASS },
	33: { name = 'Electric Bass(finger)', type = INSTRUMENT_TYPE.BASS },
	34: { name = 'Electric Bass(pick)', type = INSTRUMENT_TYPE.BASS },
	35: { name = 'Fretless Bass', type = INSTRUMENT_TYPE.BASS },
	36: { name = 'Slap Bass 0', type = INSTRUMENT_TYPE.BASS },
	37: { name = 'Slap Bass 1', type = INSTRUMENT_TYPE.BASS },
	38: { name = 'Synth Bass 0', type = INSTRUMENT_TYPE.BASS },
	39: { name = 'Synth Bass 1', type = INSTRUMENT_TYPE.BASS },
	40: { name = 'Violin', type = INSTRUMENT_TYPE.STRINGS },
	41: { name = 'Viola', type = INSTRUMENT_TYPE.STRINGS },
	42: { name = 'Cello', type = INSTRUMENT_TYPE.STRINGS },
	43: { name = 'Contrabass', type = INSTRUMENT_TYPE.STRINGS },
	44: { name = 'Tremolo Strings', type = INSTRUMENT_TYPE.STRINGS },
	45: { name = 'Pizzicato Strings', type = INSTRUMENT_TYPE.STRINGS },
	46: { name = 'Orchestral Strings', type = INSTRUMENT_TYPE.STRINGS },
	47: { name = 'Timpani', type = INSTRUMENT_TYPE.STRINGS },
	48: { name = 'String Ensemble 0', type = INSTRUMENT_TYPE.ENSEMBLE },
	49: { name = 'String Ensemble 1', type = INSTRUMENT_TYPE.ENSEMBLE },
	50: { name = 'SynthStrings 0', type = INSTRUMENT_TYPE.ENSEMBLE },
	51: { name = 'SynthStrings 1', type = INSTRUMENT_TYPE.ENSEMBLE },
	52: { name = 'Choir Aahs', type = INSTRUMENT_TYPE.ENSEMBLE },
	53: { name = 'Voice Oohs', type = INSTRUMENT_TYPE.ENSEMBLE },
	54: { name = 'Synth Voice', type = INSTRUMENT_TYPE.ENSEMBLE },
	55: { name = 'Orchestra Hit', type = INSTRUMENT_TYPE.ENSEMBLE },
	56: { name = 'Trumpet', type = INSTRUMENT_TYPE.BRASS },
	57: { name = 'Trombone', type = INSTRUMENT_TYPE.BRASS },
	58: { name = 'Tuba', type = INSTRUMENT_TYPE.BRASS },
	59: { name = 'Muted Trumpet', type = INSTRUMENT_TYPE.BRASS },
	60: { name = 'French Horn', type = INSTRUMENT_TYPE.BRASS },
	61: { name = 'Brass Section', type = INSTRUMENT_TYPE.BRASS },
	62: { name = 'SynthBrass 0', type = INSTRUMENT_TYPE.BRASS },
	63: { name = 'SynthBrass 1', type = INSTRUMENT_TYPE.BRASS },
	64: { name = 'Soprano Sax', type = INSTRUMENT_TYPE.REED },
	65: { name = 'Alto Sax', type = INSTRUMENT_TYPE.REED },
	66: { name = 'Tenor Sax', type = INSTRUMENT_TYPE.REED },
	67: { name = 'Baritone Sax', type = INSTRUMENT_TYPE.REED },
	68: { name = 'Oboe', type = INSTRUMENT_TYPE.REED },
	69: { name = 'English Horn', type = INSTRUMENT_TYPE.REED },
	70: { name = 'Bassoon', type = INSTRUMENT_TYPE.REED },
	71: { name = 'Clarinet', type = INSTRUMENT_TYPE.REED },
	72: { name = 'Piccolo', type = INSTRUMENT_TYPE.PIPE },
	73: { name = 'Flute', type = INSTRUMENT_TYPE.PIPE },
	74: { name = 'Recorder', type = INSTRUMENT_TYPE.PIPE },
	75: { name = 'Pan Flute', type = INSTRUMENT_TYPE.PIPE },
	76: { name = 'Blown Bottle', type = INSTRUMENT_TYPE.PIPE },
	77: { name = 'Skakuhachi', type = INSTRUMENT_TYPE.PIPE },
	78: { name = 'Whistle', type = INSTRUMENT_TYPE.PIPE },
	79: { name = 'Ocarina', type = INSTRUMENT_TYPE.PIPE },
	80: { name = 'Square Wave', type = INSTRUMENT_TYPE.SYNTH_LEAD },
	81: { name = 'Saw Wave', type = INSTRUMENT_TYPE.SYNTH_LEAD },
	82: { name = 'Syn. Calliope', type = INSTRUMENT_TYPE.SYNTH_LEAD },
	83: { name = 'Chiffer Lead', type = INSTRUMENT_TYPE.SYNTH_LEAD },
	84: { name = 'Charang', type = INSTRUMENT_TYPE.SYNTH_LEAD },
	85: { name = 'Solo Vox', type = INSTRUMENT_TYPE.SYNTH_LEAD },
	86: { name = '4th Saw Wave', type = INSTRUMENT_TYPE.SYNTH_LEAD },
	87: { name = 'Bass & Lead', type = INSTRUMENT_TYPE.SYNTH_LEAD },
	88: { name = 'Fantasia', type = INSTRUMENT_TYPE.SYNTH_PAD },
	89: { name = 'Warm Pad', type = INSTRUMENT_TYPE.SYNTH_PAD },
	90: { name = 'Polysynth', type = INSTRUMENT_TYPE.SYNTH_PAD },
	91: { name = 'Space Voice', type = INSTRUMENT_TYPE.SYNTH_PAD },
	92: { name = 'Bowed Glass', type = INSTRUMENT_TYPE.SYNTH_PAD },
	93: { name = 'Metal Pad', type = INSTRUMENT_TYPE.SYNTH_PAD },
	94: { name = 'Halo Pad', type = INSTRUMENT_TYPE.SYNTH_PAD },
	95: { name = 'Sweep Pad', type = INSTRUMENT_TYPE.SYNTH_PAD },
	96: { name = 'Ice Rain', type = INSTRUMENT_TYPE.SYNTH_EFFECTS },
	97: { name = 'Soundtrack', type = INSTRUMENT_TYPE.SYNTH_EFFECTS },
	98: { name = 'Crystal', type = INSTRUMENT_TYPE.SYNTH_EFFECTS },
	99: { name = 'Atmosphere', type = INSTRUMENT_TYPE.SYNTH_EFFECTS },
	100: { name = 'Brightness', type = INSTRUMENT_TYPE.SYNTH_EFFECTS },
	101: { name = 'Goblin', type = INSTRUMENT_TYPE.SYNTH_EFFECTS },
	102: { name = 'Echo Drops', type = INSTRUMENT_TYPE.SYNTH_EFFECTS },
	103: { name = 'Star Theme', type = INSTRUMENT_TYPE.SYNTH_EFFECTS },
	104: { name = 'Sitar', type = INSTRUMENT_TYPE.ETHNIC },
	105: { name = 'Banjo', type = INSTRUMENT_TYPE.ETHNIC },
	106: { name = 'Shamisen', type = INSTRUMENT_TYPE.ETHNIC },
	107: { name = 'Koto', type = INSTRUMENT_TYPE.ETHNIC },
	108: { name = 'Kalimba', type = INSTRUMENT_TYPE.ETHNIC },
	109: { name = 'Bagpipe', type = INSTRUMENT_TYPE.ETHNIC },
	110: { name = 'Fiddle', type = INSTRUMENT_TYPE.ETHNIC },
	111: { name = 'Shanai', type = INSTRUMENT_TYPE.ETHNIC },
	112: { name = 'Tinkle Bell', type = INSTRUMENT_TYPE.SOUND_EFFECTS },
	113: { name = 'Agogo', type = INSTRUMENT_TYPE.SOUND_EFFECTS },
	114: { name = 'Steel Drums', type = INSTRUMENT_TYPE.SOUND_EFFECTS },
	115: { name = 'Woodblock', type = INSTRUMENT_TYPE.SOUND_EFFECTS },
	116: { name = 'Taiko Drum', type = INSTRUMENT_TYPE.SOUND_EFFECTS },
	117: { name = 'Melodic Tom', type = INSTRUMENT_TYPE.SOUND_EFFECTS },
	118: { name = 'Synth Drum', type = INSTRUMENT_TYPE.SOUND_EFFECTS },
	119: { name = 'Reverse Cymbal', type = INSTRUMENT_TYPE.SOUND_EFFECTS },
	120: { name = 'Guitar Fret Noise', type = INSTRUMENT_TYPE.SOUND_EFFECTS },
	121: { name = 'Breath Noise', type = INSTRUMENT_TYPE.SOUND_EFFECTS },
	122: { name = 'Seashore', type = INSTRUMENT_TYPE.SOUND_EFFECTS },
	123: { name = 'Bird Tweet', type = INSTRUMENT_TYPE.SOUND_EFFECTS },
	124: { name = 'Telephone Ring', type = INSTRUMENT_TYPE.SOUND_EFFECTS },
	125: { name = 'Helicopter', type = INSTRUMENT_TYPE.SOUND_EFFECTS },
	126: { name = 'Applause', type = INSTRUMENT_TYPE.SOUND_EFFECTS },
	127: { name = 'Gunshot', type = INSTRUMENT_TYPE.SOUND_EFFECTS },
	999: { name = 'Drums', type = INSTRUMENT_TYPE.DRUMS },
}

const instrument_icons: Dictionary[INSTRUMENT_TYPE, String] = {
	INSTRUMENT_TYPE.PIANO: "res://icons/piano.png",
	INSTRUMENT_TYPE.CHROMATIC_PERCUSSION: "res://icons/xylophone.png",
	INSTRUMENT_TYPE.ORGAN: "res://icons/organ.png",
	INSTRUMENT_TYPE.GUITAR: "res://icons/guitar.png",
	INSTRUMENT_TYPE.BASS: "res://icons/electric-guitar.png",
	INSTRUMENT_TYPE.STRINGS: "res://icons/violin.png",
	INSTRUMENT_TYPE.ENSEMBLE: "res://icons/ensemble.png",
	INSTRUMENT_TYPE.BRASS: "res://icons/brass.png",
	INSTRUMENT_TYPE.REED: "res://icons/saxophone.png",
	INSTRUMENT_TYPE.PIPE: "res://icons/pipe.png",
	INSTRUMENT_TYPE.SYNTH_LEAD: "res://icons/synthesizer.png",
	INSTRUMENT_TYPE.SYNTH_PAD: "res://icons/synthesizer.png",
	INSTRUMENT_TYPE.SYNTH_EFFECTS: "res://icons/synthesizer.png",
	INSTRUMENT_TYPE.ETHNIC: "res://icons/sitar.png",
	INSTRUMENT_TYPE.SOUND_EFFECTS: "res://icons/sound-effect.png",
	INSTRUMENT_TYPE.DRUMS: "res://icons/drum-set.png",
}

const percussion_notes: Dictionary[int, String] = {
	35: 'Acoustic Bass Drum',
	36: 'Bass Drum 1',
	37: 'Side Stick',
	38: 'Acoustic Snare',
	39: 'Hand Clap',
	40: 'Electric Snare',
	41: 'Low Floor Tom',
	42: 'Closed High Hat',
	43: 'High Floor Tom',
	44: 'Pedal High Hat',
	45: 'Low Tom',
	46: 'Open High Hat',
	47: 'Low Mid Tom',
	48: 'High Mid Tom',
	49: 'Crash Cymbal 1',
	50: 'High Tom',
	51: 'Ride Cymbal 1',
	52: 'Chinese Cymbal',
	53: 'Ride Bell',
	54: 'Tambourine',
	55: 'Splash Cymbal',
	56: 'Cowbell',
	57: 'Crash Cymbal 2',
	58: 'Vibraslap',
	59: 'Ride Cymbal 2',
	60: 'High Bongo',
	61: 'Low Bongo',
	62: 'Mute High Conga',
	63: 'Open High Conga',
	64: 'Low Conga',
	65: 'High Timbale',
	66: 'Low Timbale',
	67: 'High Agogo',
	68: 'Low Agogo',
	69: 'Cabasa',
	70: 'Maracas',
	71: 'Short Whistle',
	72: 'Long Whistle',
	73: 'Short Guiro',
	74: 'Long Guiro',
	75: 'Claves',
	76: 'High Wood Block',
	77: 'Low Wood Block',
	78: 'Mute Cuica',
	79: 'Open Cuica',
	80: 'Mute Triangle',
	81: 'Open Triangle',
}
