extends Node

class_name Intruments

const instruments: Dictionary[int, Dictionary] = {
	1: { name = 'Acoustic Grand', type = 'PIANO'},
	2: { name = 'Bright Acoustic', type = 'PIANO'},
	3: { name = 'Electric Grand', type = 'PIANO'},
	4: { name = 'Honky-Tonk', type = 'PIANO'},
	5: { name = 'Electric Piano 1', type = 'PIANO'},
	6: { name = 'Electric Piano 2', type = 'PIANO'},
	7: { name = 'Harpsichord', type = 'PIANO'},
	8: { name = 'Clavinet', type = 'PIANO'},
	9: { name = 'Celesta', type = 'CHROM. PERCUS.'},
	10: { name = 'Glockenspiel', type = 'CHROM. PERCUS.'},
	11: { name = 'Music Box', type = 'CHROM. PERCUS.'},
	12: { name = 'Vibraphone', type = 'CHROM. PERCUS.'},
	13: { name = 'Marimba', type = 'CHROM. PERCUS.'},
	14: { name = 'Xylophone', type = 'CHROM. PERCUS.'},
	15: { name = 'Tubular Bells', type = 'CHROM. PERCUS.'},
	16: { name = 'Dulcimer', type = 'CHROM. PERCUS.'},
	17: { name = 'Drawbar Organ', type = 'ORGAN'},
	18: { name = 'Percussive Organ', type = 'ORGAN'},
	19: { name = 'Rock Organ', type = 'ORGAN'},
	20: { name = 'Church Organ', type = 'ORGAN'},
	21: { name = 'Reed Organ', type = 'ORGAN'},
	22: { name = 'Accoridan', type = 'ORGAN'},
	23: { name = 'Harmonica', type = 'ORGAN'},
	24: { name = 'Tango Accordian', type = 'ORGAN'},
	25: { name = 'Nylon String Guitar', type = 'GUITAR'},
	26: { name = 'Steel String Guitar', type = 'GUITAR'},
	27: { name = 'Electric Jazz Guitar', type = 'GUITAR'},
	28: { name = 'Electric Clean Guitar', type = 'GUITAR'},
	29: { name = 'Electric Muted Guitar', type = 'GUITAR'},
	30: { name = 'Overdriven Guitar', type = 'GUITAR'},
	31: { name = 'Distortion Guitar', type = 'GUITAR'},
	32: { name = 'Guitar Harmonics', type = 'GUITAR'},
	33: { name = 'Acoustic Bass', type = 'BASS' },
	34: { name = 'Electric Bass(finger)', type = 'BASS' },
	35: { name = 'Electric Bass(pick)', type = 'BASS' },
	36: { name = 'Fretless Bass', type = 'BASS' },
	37: { name = 'Slap Bass 1', type = 'BASS' },
	38: { name = 'Slap Bass 2', type = 'BASS' },
	39: { name = 'Synth Bass 1', type = 'BASS' },
	40: { name = 'Synth Bass 2', type = 'BASS' },
	41: { name = 'Violin', type = 'SOLO STRINGS' },
	42: { name = 'Viola', type = 'SOLO STRINGS' },
	43: { name = 'Cello', type = 'SOLO STRINGS' },
	44: { name = 'Contrabass', type = 'SOLO STRINGS' },
	45: { name = 'Tremolo Strings', type = 'SOLO STRINGS' },
	46: { name = 'Pizzicato Strings', type = 'SOLO STRINGS' },
	47: { name = 'Orchestral Strings', type = 'SOLO STRINGS' },
	48: { name = 'Timpani', type = 'SOLO STRINGS' },
	49: { name = 'String Ensemble 1', type = 'ENSEMBLE' },
	50: { name = 'String Ensemble 2', type = 'ENSEMBLE' },
	51: { name = 'SynthStrings 1', type = 'ENSEMBLE' },
	52: { name = 'SynthStrings 2', type = 'ENSEMBLE' },
	53: { name = 'Choir Aahs', type = 'ENSEMBLE' },
	54: { name = 'Voice Oohs', type = 'ENSEMBLE' },
	55: { name = 'Synth Voice', type = 'ENSEMBLE' },
	56: { name = 'Orchestra Hit', type = 'ENSEMBLE' },
	57: { name = 'Trumpet', type = 'BRASS' },
	58: { name = 'Trombone', type = 'BRASS' },
	59: { name = 'Tuba', type = 'BRASS' },
	60: { name = 'Muted Trumpet', type = 'BRASS' },
	61: { name = 'French Horn', type = 'BRASS' },
	62: { name = 'Brass Section', type = 'BRASS' },
	63: { name = 'SynthBrass 1', type = 'BRASS' },
	64: { name = 'SynthBrass 2', type = 'BRASS' },
	65: { name = 'Soprano Sax', type = 'REED' },
	66: { name = 'Alto Sax', type = 'REED' },
	67: { name = 'Tenor Sax', type = 'REED' },
	68: { name = 'Baritone Sax', type = 'REED' },
	69: { name = 'Oboe', type = 'REED' },
	70: { name = 'English Horn', type = 'REED' },
	71: { name = 'Bassoon', type = 'REED' },
	72: { name = 'Clarinet', type = 'REED' },
	73: { name = 'Piccolo', type = 'PIPE' },
	74: { name = 'Flute', type = 'PIPE' },
	75: { name = 'Recorder', type = 'PIPE' },
	76: { name = 'Pan Flute', type = 'PIPE' },
	77: { name = 'Blown Bottle', type = 'PIPE' },
	78: { name = 'Skakuhachi', type = 'PIPE' },
	79: { name = 'Whistle', type = 'PIPE' },
	80: { name = 'Ocarina', type = 'PIPE' },
	81: { name = 'Square Wave', type = 'SYNTH LEAD' },
	82: { name = 'Saw Wave', type = 'SYNTH LEAD' },
	83: { name = 'Syn. Calliope', type = 'SYNTH LEAD' },
	84: { name = 'Chiffer Lead', type = 'SYNTH LEAD' },
	85: { name = 'Charang', type = 'SYNTH LEAD' },
	86: { name = 'Solo Vox', type = 'SYNTH LEAD' },
	87: { name = '5th Saw Wave', type = 'SYNTH LEAD' },
	88: { name = 'Bass& Lead', type = 'SYNTH LEAD' },
	89: { name = 'Fantasia', type = 'SYNTH PAD' },
	90: { name = 'Warm Pad', type = 'SYNTH PAD' },
	91: { name = 'Polysynth', type = 'SYNTH PAD' },
	92: { name = 'Space Voice', type = 'SYNTH PAD' },
	93: { name = 'Bowed Glass', type = 'SYNTH PAD' },
	94: { name = 'Metal Pad', type = 'SYNTH PAD' },
	95: { name = 'Halo Pad', type = 'SYNTH PAD' },
	96: { name = 'Sweep Pad', type = 'SYNTH PAD' },
	97: { name = 'Ice Rain', type = 'SYNTH EFFECTS' },
	98: { name = 'Soundtrack', type = 'SYNTH EFFECTS' },
	99: { name = 'Crystal', type = 'SYNTH EFFECTS' },
	100: { name = 'Atmosphere', type = 'SYNTH EFFECTS' },
	101: { name = 'Brightness', type = 'SYNTH EFFECTS' },
	102: { name = 'Goblin', type = 'SYNTH EFFECTS' },
	103: { name = 'Echo Drops', type = 'SYNTH EFFECTS' },
	104: { name = 'Star Theme', type = 'SYNTH EFFECTS' },
	105: { name = 'Sitar', type = 'ETHNIC' },
	106: { name = 'Banjo', type = 'ETHNIC' },
	107: { name = 'Shamisen', type = 'ETHNIC' },
	108: { name = 'Koto', type = 'ETHNIC' },
	109: { name = 'Kalimba', type = 'ETHNIC' },
	110: { name = 'Bagpipe', type = 'ETHNIC' },
	111: { name = 'Fiddle', type = 'ETHNIC' },
	112: { name = 'Shanai', type = 'ETHNIC' },
	113: { name = 'Tinkle Bell', type = 'PERCUSSIVE' },
	114: { name = 'Agogo', type = 'PERCUSSIVE' },
	115: { name = 'Steel Drums', type = 'PERCUSSIVE' },
	116: { name = 'Woodblock', type = 'PERCUSSIVE' },
	117: { name = 'Taiko Drum', type = 'PERCUSSIVE' },
	118: { name = 'Melodic Tom', type = 'PERCUSSIVE' },
	119: { name = 'Synth Drum', type = 'PERCUSSIVE' },
	120: { name = 'Reverse Cymbal', type = 'PERCUSSIVE' },
	121: { name = 'Guitar Fret Noise', type = 'SOUND EFFECTS' },
	122: { name = 'Breath Noise', type = 'SOUND EFFECTS' },
	123: { name = 'Seashore', type = 'SOUND EFFECTS' },
	124: { name = 'Bird Tweet', type = 'SOUND EFFECTS' },
	125: { name = 'Telephone Ring', type = 'SOUND EFFECTS' },
	126: { name = 'Helicopter', type = 'SOUND EFFECTS' },
	127: { name = 'Applause', type = 'SOUND EFFECTS' },
	128: { name = 'Gunshot', type = 'SOUND EFFECTS' },
};
